[package]
name = "mbus-rs"
version = "1.0.0"
authors = ["John Fabienke <jfabienke@arqitekta.com>"]
edition = "2021"
description = "A Rust crate for M-Bus (Meter-Bus) protocol communication"
repository = "https://github.com/jfabienke/mbus-rs"
license = "MIT"

anyhow = "1.0"

[dev-dependencies]
criterion = "0.5"
proptest = "1.7.0"
tokio-test = "0.4.4"

[[bench]]
name = "parsing_benchmark"
harness = false
