[package]
name = "mbus-rs"
version = "0.1.0"
authors = ["John Fabienke <jfabienke@arqitekta.com>"]
edition = "2021"
description = "A Rust crate for M-Bus (Meter-Bus) protocol communication"
repository = "https://github.com/jfabienke/mbus-rs"
license = "MIT"

[dependencies]
thiserror = "2.0"
tokio = { version = "1.47", features = ["full"] }
tokio-serial = "5.4"
log = "0.4"
env_logger = "0.10"
nom = "7.1"
num-traits = "0.2"
clap = "4.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "parsing_benchmark"
harness = false
