# Cargo configuration for cross-compilation targets

[target.aarch64-unknown-linux-gnu]
# Raspberry Pi 4 (64-bit) / Raspberry Pi 5
linker = "aarch64-linux-musl-gcc"
# Enable crypto extensions for Pi 5 (Cortex-A76)
# For Pi 4 (Cortex-A72), remove +aes,+sha2,+crypto
rustflags = [
    "-C", "target-cpu=cortex-a76",
    "-C", "target-features=+aes,+sha2,+neon,+crc,+crypto",
    "-C", "opt-level=3",
]

[target.armv7-unknown-linux-gnueabihf]  
# Raspberry Pi 4 (32-bit) / Raspberry Pi 3/2/Zero
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabihf]
# Raspberry Pi 1/Zero (original ARM11)
linker = "arm-linux-gnueabihf-gcc"

# Build optimizations for embedded targets
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
overflow-checks = false
incremental = false
rpath = false

[profile.release-with-debug]
inherits = "release"
debug = true

# Raspberry Pi specific features
[features]
default = []
raspberry-pi = ["rppal"]
raspberry-pi-4 = ["raspberry-pi"]
raspberry-pi-5 = ["raspberry-pi"] 
gpio-interrupt = ["raspberry-pi"]
hardware-spi = ["raspberry-pi"]